language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t moehadidi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true moehadidi/react-test npm test

after_success:
  - docker build -t moehadidi/multi-client ./client
  - docker build -t moehadidi/mutli-nginx ./nginx
  - docker build -t moehadidi/mutli-server ./server
  - docker build -t moehadidi/mutli-worker ./worker
  # Login into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
  # Take those images and push them to docker hub
  - docker push moehadidi/multi-client
  - docker push moehadidi/mutli-nginx
  - docker push moehadidi/mutli-server
  - docker push moehadidi/mutli-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-424017959099
  bucket_path: docker_multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  #    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
